logging:
  level:
    org:
      coderclan: debug
      springframework:
        cloud:
          stream: trace
server:
  port: 0
spring:
  h2:
    console:
      enabled: true
      path: /h2

  cloud:
    stream:
      default:
        consumer:
          concurrency: 3
  datasource:
    url: jdbc:h2:mem:whistle-example-consumer
    username: sa
    password: sa
    driverClassName: org.h2.Driver